### ISSUE TITLE
[PE-D][Tester D] Able to assign two persons of same name despite warning in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-4/tp#127]
![image.png](https://raw.githubusercontent.com/mahadhir247/ped/main/files/745c6af6-66e5-4d9e-9ee2-67429a2e57e1.png)

![image.png](https://raw.githubusercontent.com/mahadhir247/ped/main/files/0ce39675-8f4a-453f-98f0-e888efc535d3.png)

- Able to add persons with non-unique names into the same project
- First instance was added using `assign team`, second instance using `add person`
- User guide warns that person names have to be unique
- Unsure which is intended outcome thus have decided to set this as a documentation bug

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: mahadhir247/ped#6

**Comment by Lin-Shuang-Shuang** [comment]
cannot be fixed, but should be mentioned in UG

**Comment by modembcc** [comment]
Duplicate
