### ISSUE TITLE
[PE-D][Tester A] Project Status Not Displayed in App (Incomplete)

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W08-4/tp#139]
## Description
After setting a status to "incomplete" for a project using the `set status` command in the application, the project status is not displayed anywhere in the app interface. Users expect to see the project status alongside other project details, but it is missing from the interface.

## Steps to Reproduce
1. Open the application.
2. Add a project by entering `add project CS2101 Presentation`.
3. Set status as "incomplete" for the selected project by entering `set status incomplete /of CS2101 Presentation`.
4. Look for the project status in the app interface.

## Expected
After setting a status for a project as incomplete, users should be able to see the project status "incomplete" displayed in the app interface, providing them with important project information at a glance.

## Actual
The project status "incomplete" is not displayed anywhere in the app interface after setting it, leaving users unaware of the current status of the project.

![image.png](https://raw.githubusercontent.com/ashleyy2444/ped/main/files/6545786e-87b6-4ee5-8cce-760881dc9ba6.png)

## Note
This issue hinders users from easily accessing important project information, potentially leading to confusion or mismanagement of projects. Displaying the project status in the app interface would improve usability and help users better track the progress of their projects.

## Ways to improve product
For project status set as "complete", the panel that is labelled 'Showing Project: CS2101 Presentation' can be coloured green. For project status set as "incomplete", that panel can be coloured red.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ashleyy2444/ped#7

**Comment by modembcc** [comment]
Add incomplete status to ui

**Comment by ananya21** [comment]
I think we should discuss whether the user guide should specify incomplete project status doesn't show up and the user can assume the project is ongoing, I'm still unsure of whether editing the UI is allowed or not allowed
