### ISSUE TITLE
[PE-D][Tester A] Inconsistent Selection of Team Member for Task Assignment

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W08-4/tp#142]
## Description
When assigning a task to a team member in a project where there are multiple team members with the same name, the application consistently selects the first occurrence of the name for task assignment. However, there are instances where users may want to assign the task to a specific person among the duplicates, such as the third person of the same name in the list of team members.

## Steps to Reproduce
1. Open the application.
2. Add a project by entering `add project Duke chatbot`.
3. Assign the team by entering `assign team Joe, Joe, Joe, Joe, Cody /to Duke chatbot`.
4. Assign a member to do the task by entering `assign person Joe /to Rename Duke /in Duke chatbot`.
5. Enter `show project Duke chatbot` to see the updated member assigned to the task and observe that only 1 'Joe' is assigned to the task.

### Expected
When assigning a task to a team member named "Joe", users should be provided with the option to select which specific "Joe" among the duplicates to assign the task to, or the application should prompt for clarification if there are multiple team members with the same name.

### Actual
The application automatically assigns the task to the first occurrence of "Joe" in the list of team members, without providing an option for users to specify which "Joe" to assign the task to.

![image.png](https://raw.githubusercontent.com/ashleyy2444/ped/main/files/74b18b1e-fc2e-41cb-bc0e-01340725ccad.png)

### Note
This issue can lead to misassignment of tasks and confusion among users, especially in projects with multiple team members sharing the same name. Providing users with the ability to specify which team member to assign the task to would improve the flexibility and usability of the task assignment feature.

## How to improve product
If met with people having the same name, `assign person` function can include an index, e.g., `assign person <NAME> <INDEX> /to <TASK_NAME> /in <PROJECT_NAME>`. The purpose of the index is to identify specifically which person of that particular name to assign the task to. 

For example, 
Project: Duke chatbot
Team members: Joe, Joe, Joe, Joe, Cody
If the third person is to be assigned the task, the command would be `assign person Joe 3 /to Rename Duke /in Duke chatbot`

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ashleyy2444/ped#10

**Comment by modembcc** [comment]
Fixed, can close after test

**Comment by Lin-Shuang-Shuang** [comment]
cannot be fixed in v1.4
